
name: Automate Code Fetch and Protocol Extraction

on:
  schedule:
    # Her 5 dakikada bir çalışacak şekilde zamanlayın
    - cron: "*/5 * * * *"  # Her 5 dakikada bir
  workflow_dispatch:  # El ile de çalıştırılabilir

jobs:
  automate:
    runs-on: ubuntu-latest  # Ubuntu ortamında çalışacak

    steps:
    # Python ortamını kurun
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Depo içeriğini çek
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Gerekli kütüphaneleri yükleyin
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # requirements.txt dosyasında gerekli kütüphaneleri belirtmelisiniz

    # Kodu çalıştırın (otomasyon işlemi)
    - name: Run automation script
      run: |
        python automate.py  # Burada 'automate.py' sizin Python script dosyanız olmalı
        # Eğer script'in başka adla oluyorsa ona göre değiştirin

    # Değişiklikleri GitHub'a yükle (eğer dosyada değişiklik olduysa)
    - name: Commit and push changes
      run: |
        git config --global user.name "YourName"
        git config --global user.email "youremail@example.com"
        git add .
        git commit -m "Automated update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token kullanarak push yapabilmek için
