name: Auto Update Subscription

on:
  schedule:
    - cron: "*/5 * * * *"  # Her 5 dakikada bir çalıştır
  workflow_dispatch:  # Manuel olarak çalıştırabilmek için

jobs:
  update-config:
    runs-on: ubuntu-latest  # Ubuntu üzerinde çalışacak

    steps:
      - name: Repozitory'yi Klonla
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerekli Paketleri Kur
        run: pip install -r requirements.txt  # Bu kısmı düzgün hizaladım

      - name: Python Scriptini Çalıştır
        run: python script.py  # Burada kendi Python scriptini çalıştır

      - name: Güncellenen Dosyayı Commit Et ve Pushla
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Otomatik Güncelleme: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
